### ISSUE TITLE
Option to copy the unarchived directory's contents?

### ISSUE THREAD

**Issue by philipbjorge** [bitrise-steplib/steps-resource-archive#5]
Hi,
What do you think about adding an option to allow copying the unarchived folder's contents instead of the entire folder?

Use case:
1. Download a zip file containing android licenses
2. Extract the files to unarchived/
3. Copy the license files into /opt/android-sdk-linux/licenses/

Right now, the step copies the unarchived folder and it seems silly to have to have an extra shell step to fix it.

**Comment by viktorbenei** [comment]
Sounds like a great idea - if you have the time feel free to send us a pull request!

**Comment by viktorbenei** [comment]
One more thing, did you try to add a trailing `/` to the extract to path param? E.g. instead of `/opt/android-sdk-linux/licenses` using `/opt/android-sdk-linux/licenses/`?
